services:
  questa:
    build:
      args:
        - USER
        - UID
        - GID
      context: .
    user: $UID:$GID
    hostname: ${HOSTNAME}
    dns_search: ${DOMAIN}
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - MGLS_LICENSE_FILE


